name: CustomRecipes
description: The CustomRecipes plugin, revamped for 1.12
version: 2.0.0-SNAPSHOT
author: Jannyboy11
main: com.gmail.jannyboy11.customrecipes.CustomRecipesPlugin
website: https://www.spigotmc.org/resources/custom-recipes.11440/

commands:
  addrecipe:
    description: Create a new recipe
    usage: /addrecipe <type> <args>
    permission: customrecipes.addrecipe
  removerecipe:
    description: Remove a recipe
    usage: /removerecipe <type> <args>
    permission: customrecipes.removerecipe
  listrecipes:
    description: List all recipes of a type
    usage: /listrecipes <type>
    permission: customrecipes.listrecipes
  migraterecipes:
    description: Migrate recipes from CustomRecipes v1.0.5 and lower to v2.0.0
    usage: /migraterecipes
    permission: customrecipes.migraterecipes

permissions:
  customrecipes.addrecipe:
    description: Allows access to /addrecipe
    default: op
  customrecipes.removerecipe:
    description: Allows access to /removerecipe
    default: op
  customrecipes.migraterecipes:
    description: Allows access to /migraterecipes
    default: op

  customrecipes.listrecipes:
    description: Allows access to /listrecipes
    default: true