name: ${project.artifactId}
description: ${project.description}
version: ${project.version}
author: Jannyboy11
main: com.gmail.jannyboy11.customrecipes.CustomRecipesPlugin
website: https://www.spigotmc.org/resources/custom-recipes.11440/

commands:
  managerecipes:
    description: Create a new recipe
    usage: /managerecipes
    permission: customrecipes.manage
    aliases: [manrecipes, mrecipes, adminrecipes, arecipes, mr, ar]
  migraterecipes:
    description: Migrate recipes from CustomRecipes v2.2.1 to v3.0.0
    usage: /migraterecipes
    permission: customrecipes.migrate

permissions:
  customrecipes.manage:
    description: Allows access to /addrecipe
    default: op
  customrecipes.migrate:
    description: Allows access to /migraterecipes
    default: op